# Generated by Django 5.2.1 on 2025-05-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('seats', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('previous_school', models.CharField(max_length=200)),
                ('grade_10_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_12_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('birth_certificate', models.FileField(null=True, upload_to='documents/')),
                ('marksheet_10', models.FileField(null=True, upload_to='documents/')),
                ('marksheet_12', models.FileField(null=True, upload_to='documents/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.course')),
            ],
        ),
    ]
